# Generated by Django 4.0.1 on 2022-04-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash_app', '0002_user_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=190)),
                ('mpesacontact', models.TextField(max_length=190)),
                ('amount', models.TextField(max_length=190)),
            ],
        ),
    ]
