# Generated by Django 4.0.4 on 2022-04-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash_app', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Requirements',
            new_name='requirements',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Select_service',
            new_name='select_service',
        ),
    ]
